name: TownyMenus
main: io.github.townyadvanced.townymenus.TownyMenus
version: ${version}
api-version: 1.18
author: Warriorrr
website: 'http://townyadvanced.github.io'
depend: [Towny]

commands:
  townymenu:
    aliases:
      - tmenu
      - townygui
      - tgui
    permission: townymenus.command.townymenu

permissions:
  townymenus.command.*:
    default: op
    children:
      townymenus.command.townymenu: true

  townymenus.command.townymenu:
    default: true
